### ISSUE TITLE
Energy Score stopped working in 2023.5.0b1

### ISSUE THREAD

**Issue by smarthomejunkie** [knudsvik/EnergyScore#111]
## Version of the custom_component
V1.3.2

## Describe the bug
The energy score integration stopped working in HA 2023.5.0b1

The error on an energy score card is: Failed to set up: Import error

**Comment by knudsvik** [comment]
Thanks for reporting! I have created a fix for this which I believe will fix this issue. Version 1.3.3 should be available in HACS real soon. Please let me know if that helps @smarthomejunkie
