### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'platform'

### ISSUE THREAD

**Issue by kamaradclimber** [knudsvik/EnergyScore#51]
## Version of the custom_component

0.3.1

## Configuration

```yaml
 - platform: energyscore
    name: House Energy Score
    unique_id: a6e5f61a-0761-478a-8520-87612e0c1ea5
    price_entity: sensor.electricity_cost
    energy_entity: sensor.home_energy_meter_gen5_electric_consumed_kwh
```

## Describe the bug

Sensor initialization is throwing an error at https://github.com/knudsvik/EnergyScore/blob/master/custom_components/energyscore/sensor.py#L114-L116. I assume it happens because the price_entity is not setup *yet* when the sensor is built.

I've confirmed this hypothesis by simply removing the line (the integration is then working as expected).

I would suggest to delay this piece of code to later (`async_added_to_hass` or later in `process_new_data` since there is no way to know the order of entity bootstrap as far as I know).

## Debug log

```text
2022-12-22 18:29:13.546 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up energyscore platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/energyscore/sensor.py", line 63, in async_setup_platform
    async_add_entities([EnergyScore(hass, config)], update_before_add=False)
  File "/config/custom_components/energyscore/sensor.py", line 116, in __init__
    if entity_reg.async_get(self._price_entity).platform == "nordpool":
AttributeError: 'NoneType' object has no attribute 'platform'
```

**Comment by knudsvik** [comment]
Thanks for reporting! I think this can be solved with better async handling, and that would be preferable as it only runs this when creating the sensor once instead of at every update as suggested in your PR. 

I'll have a look at it tonight!

**Comment by knudsvik** [comment]
Asked for advice on [Discord](https://discord.com/channels/330944238910963714/554842238073700352/1055720864378785792). There is a way to do this apparently, but probably will take time for me to implement as I need to understand it better. Can probably go down your route in the mean time to get this fix out.

**Comment by kamaradclimber** [comment]
We can take time to find the fix that is appropriate ( I have a local fix that works for me so I can use the integration meanwhile).
However I'd be surprised if it happened to me only so I wonder if something in my setup leads me to a special behavior that other users would not have :thinking:
